import { z } from 'zod';
import { query, withTransaction } from '../../database/db.js';
import { send } from '../../utils/response.js';

const uuid = z.string().uuid();
const statuses = ['OFFLINE','AVAILABLE','READY','IN_TRIP','AT_STOP','AT_TERMINAL','RETURNING','OUT_OF_SERVICE','EMERGENCY','GPS_ERROR'];
const simOperators = ['DJEZZY','MOBILIS'];
const busSchema = z.object({operatorId:uuid.nullable().optional(),busNumber:z.string().trim().min(1).max(50),capacity:z.coerce.number().int().positive().max(1000),status:z.enum(statuses).optional(),active:z.boolean().optional()}).strict();
const deviceSchema = z.object({busId:uuid.nullable().optional(),deviceIdentifier:z.string().trim().min(1).max(100),simOperator:z.enum(simOperators),active:z.boolean().optional()}).strict();
const driverSchema = z.object({operatorId:uuid.nullable().optional(),driverNumber:z.string().trim().min(1).max(50),firstName:z.string().trim().min(1).max(100),lastName:z.string().trim().min(1).max(100),active:z.boolean().optional()}).strict();
function parsed(req,s){const r=s.safeParse(req.body);if(!r.success){const e=new Error('Validation failed');e.status=400;e.code='VALIDATION_ERROR';e.details=r.error.flatten();throw e;}return r.data;}
function id(req){const r=uuid.safeParse(req.params.id);if(!r.success){const e=new Error('Invalid UUID');e.status=400;e.code='VALIDATION_ERROR';throw e;}return r.data;}
async function audit(c,req,action,type,entityId,before,after){await c.query('INSERT INTO audit_log(actor_admin_id,action,entity_type,entity_id,before_data,after_data) VALUES($1,$2,$3,$4,$5,$6)',[req.auth.id,action,type,entityId,before?JSON.stringify(before):null,after?JSON.stringify(after):null]);}
async function operator(c,operatorId){if(operatorId==null)return;const r=await c.query('SELECT id,active FROM operators WHERE id=$1',[operatorId]);if(!r.rows[0]){const e=new Error('Operator not found');e.status=404;throw e;}if(!r.rows[0].active){const e=new Error('Operator is inactive');e.status=400;throw e;}}
async function bus(c,busId){if(busId==null)return;const r=await c.query('SELECT id,active FROM buses WHERE id=$1',[busId]);if(!r.rows[0]){const e=new Error('Bus not found');e.status=404;throw e;}if(!r.rows[0].active){const e=new Error('Cannot assign a device to an inactive bus');e.status=400;throw e;}}

export async function listBuses(req,res){const r=await query(`SELECT b.id,b.operator_id AS "operatorId",o.name AS "operatorName",b.bus_number AS "busNumber",b.capacity,b.status,b.active,b.created_at AS "createdAt" FROM buses b LEFT JOIN operators o ON o.id=b.operator_id ORDER BY b.bus_number`);send(res,r.rows);}
export async function createBus(req,res){const b=parsed(req,busSchema);const r=await withTransaction(async c=>{await operator(c,b.operatorId);const n=(await c.query(`INSERT INTO buses(operator_id,bus_number,capacity,status,active) VALUES($1,$2,$3,$4,$5) RETURNING id,operator_id AS "operatorId",bus_number AS "busNumber",capacity,status,active,created_at AS "createdAt"`,[b.operatorId??null,b.busNumber,b.capacity,b.status??'OFFLINE',b.active??true])).rows[0];await audit(c,req,'CREATE','BUS',n.id,null,n);return n;});send(res,r,201);}
export async function updateBus(req,res){const b=parsed(req,busSchema),busId=id(req);const r=await withTransaction(async c=>{const old=(await c.query('SELECT * FROM buses WHERE id=$1 FOR UPDATE',[busId])).rows[0];if(!old){const e=new Error('Bus not found');e.status=404;throw e;}await operator(c,b.operatorId);if(String(b.operatorId??'')!==String(old.operator_id??'')){const t=(await c.query('SELECT id FROM trips WHERE bus_id=$1 LIMIT 1',[busId])).rows[0];if(t){const e=new Error('Cannot change the operator of a bus referenced by trips');e.status=409;e.code='BUS_OPERATOR_LOCKED';throw e;}}if(b.active===false){const d=(await c.query('SELECT id FROM devices WHERE bus_id=$1 AND active=true',[busId])).rows[0];if(d){const e=new Error('Cannot deactivate a bus with an active device');e.status=409;e.code='BUS_HAS_ACTIVE_DEVICE';throw e;}}const n=(await c.query(`UPDATE buses SET operator_id=$1,bus_number=$2,capacity=$3,status=$4,active=$5 WHERE id=$6 RETURNING id,operator_id AS "operatorId",bus_number AS "busNumber",capacity,status,active,created_at AS "createdAt"`,[b.operatorId??null,b.busNumber,b.capacity,b.status??old.status,b.active??old.active,busId])).rows[0];await audit(c,req,'UPDATE','BUS',n.id,old,n);return n;});send(res,r);}
export async function deleteBus(req,res){const busId=id(req);const r=await withTransaction(async c=>{const old=(await c.query('SELECT * FROM buses WHERE id=$1 FOR UPDATE',[busId])).rows[0];if(!old){const e=new Error('Bus not found');e.status=404;throw e;}if((await c.query('SELECT id FROM trips WHERE bus_id=$1 LIMIT 1',[busId])).rows[0]){const e=new Error('Cannot delete a bus referenced by trips; deactivate it instead');e.status=409;e.code='BUS_IN_USE';throw e;}await c.query('DELETE FROM devices WHERE bus_id=$1',[busId]);await c.query('DELETE FROM buses WHERE id=$1',[busId]);await audit(c,req,'DELETE','BUS',busId,old,null);return{id:busId};});send(res,r);}

export async function listDevices(req,res){const r=await query(`SELECT d.id,d.bus_id AS "busId",b.bus_number AS "busNumber",d.device_identifier AS "deviceIdentifier",d.sim_operator AS "simOperator",d.active,d.created_at AS "createdAt" FROM devices d LEFT JOIN buses b ON b.id=d.bus_id ORDER BY d.device_identifier`);send(res,r.rows);}
export async function createDevice(req,res){const b=parsed(req,deviceSchema);const r=await withTransaction(async c=>{await bus(c,b.busId);const n=(await c.query(`INSERT INTO devices(bus_id,device_identifier,sim_operator,active) VALUES($1,$2,$3,$4) RETURNING id,bus_id AS "busId",device_identifier AS "deviceIdentifier",sim_operator AS "simOperator",active,created_at AS "createdAt"`,[b.busId??null,b.deviceIdentifier,b.simOperator,b.active??true])).rows[0];await audit(c,req,'CREATE','DEVICE',n.id,null,n);return n;});send(res,r,201);}
export async function updateDevice(req,res){const b=parsed(req,deviceSchema),deviceId=id(req);const r=await withTransaction(async c=>{const old=(await c.query('SELECT * FROM devices WHERE id=$1 FOR UPDATE',[deviceId])).rows[0];if(!old){const e=new Error('Device not found');e.status=404;throw e;}await bus(c,b.busId);const n=(await c.query(`UPDATE devices SET bus_id=$1,device_identifier=$2,sim_operator=$3,active=$4 WHERE id=$5 RETURNING id,bus_id AS "busId",device_identifier AS "deviceIdentifier",sim_operator AS "simOperator",active,created_at AS "createdAt"`,[b.busId??null,b.deviceIdentifier,b.simOperator,b.active??old.active,deviceId])).rows[0];await audit(c,req,'UPDATE','DEVICE',n.id,old,n);return n;});send(res,r);}
export async function deleteDevice(req,res){const deviceId=id(req);const r=await withTransaction(async c=>{const old=(await c.query('SELECT * FROM devices WHERE id=$1 FOR UPDATE',[deviceId])).rows[0];if(!old){const e=new Error('Device not found');e.status=404;throw e;}if((await c.query('SELECT id FROM telemetry WHERE device_id=$1 LIMIT 1',[deviceId])).rows[0]){const e=new Error('Cannot delete a device referenced by telemetry; deactivate it instead');e.status=409;e.code='DEVICE_IN_USE';throw e;}await c.query('DELETE FROM devices WHERE id=$1',[deviceId]);await audit(c,req,'DELETE','DEVICE',deviceId,old,null);return{id:deviceId};});send(res,r);}

export async function listDrivers(req,res){const r=await query(`SELECT d.id,d.operator_id AS "operatorId",o.name AS "operatorName",d.driver_number AS "driverNumber",d.first_name AS "firstName",d.last_name AS "lastName",d.active,d.created_at AS "createdAt" FROM drivers d LEFT JOIN operators o ON o.id=d.operator_id ORDER BY d.last_name,d.first_name`);send(res,r.rows);}
export async function createDriver(req,res){const b=parsed(req,driverSchema);const r=await withTransaction(async c=>{await operator(c,b.operatorId);const n=(await c.query(`INSERT INTO drivers(operator_id,driver_number,first_name,last_name,active) VALUES($1,$2,$3,$4,$5) RETURNING id,operator_id AS "operatorId",driver_number AS "driverNumber",first_name AS "firstName",last_name AS "lastName",active,created_at AS "createdAt"`,[b.operatorId??null,b.driverNumber,b.firstName,b.lastName,b.active??true])).rows[0];await audit(c,req,'CREATE','DRIVER',n.id,null,n);return n;});send(res,r,201);}
export async function updateDriver(req,res){const b=parsed(req,driverSchema),driverId=id(req);const r=await withTransaction(async c=>{const old=(await c.query('SELECT * FROM drivers WHERE id=$1 FOR UPDATE',[driverId])).rows[0];if(!old){const e=new Error('Driver not found');e.status=404;throw e;}await operator(c,b.operatorId);if(String(b.operatorId??'')!==String(old.operator_id??'')){const t=(await c.query('SELECT id FROM trips WHERE driver_id=$1 LIMIT 1',[driverId])).rows[0];if(t){const e=new Error('Cannot change the operator of a driver referenced by trips');e.status=409;e.code='DRIVER_OPERATOR_LOCKED';throw e;}}if(b.active===false&&(await c.query(`SELECT id FROM trips WHERE driver_id=$1 AND ended_at IS NULL LIMIT 1`,[driverId])).rows[0]){const e=new Error('Cannot deactivate a driver assigned to an open trip');e.status=409;e.code='DRIVER_ON_OPEN_TRIP';throw e;}const n=(await c.query(`UPDATE drivers SET operator_id=$1,driver_number=$2,first_name=$3,last_name=$4,active=$5 WHERE id=$6 RETURNING id,operator_id AS "operatorId",driver_number AS "driverNumber",first_name AS "firstName",last_name AS "lastName",active,created_at AS "createdAt"`,[b.operatorId??null,b.driverNumber,b.firstName,b.lastName,b.active??old.active,driverId])).rows[0];await audit(c,req,'UPDATE','DRIVER',n.id,old,n);return n;});send(res,r);}
export async function deleteDriver(req,res){const driverId=id(req);const r=await withTransaction(async c=>{const old=(await c.query('SELECT * FROM drivers WHERE id=$1 FOR UPDATE',[driverId])).rows[0];if(!old){const e=new Error('Driver not found');e.status=404;throw e;}if((await c.query('SELECT id FROM trips WHERE driver_id=$1 LIMIT 1',[driverId])).rows[0]){const e=new Error('Cannot delete a driver referenced by trips; deactivate instead');e.status=409;e.code='DRIVER_IN_USE';throw e;}await c.query('DELETE FROM drivers WHERE id=$1',[driverId]);await audit(c,req,'DELETE','DRIVER',driverId,old,null);return{id:driverId};});send(res,r);}
