import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { query, withTransaction } from '../../database/db.js';
import { env } from '../../config/env.js';
import { ok, fail } from '../../utils/response.js';
const phone=z.string().regex(/^\+[1-9]\d{7,14}$/,'phone must be E.164');
const otp=z.string().regex(/^\d{6}$/,'OTP must contain 6 digits');
export const passengerPhoneSchema=phone;
export const passengerOtpSchema=otp;
const profile=z.object({firstName:z.string().trim().min(1).max(100),lastName:z.string().trim().min(1).max(100),email:z.string().email().max(254).optional(),dateOfBirth:z.string().date().optional(),nationalId:z.string().trim().max(100).optional(),studentInfo:z.record(z.string(),z.any()).optional(),companyInfo:z.record(z.string(),z.any()).optional()}).strict();
function token(id){return jwt.sign({sub:id,typ:'PASSENGER'},env.JWT_SECRET,{expiresIn:env.JWT_EXPIRES_IN,algorithm:'HS256'});}
function devCode(){return process.env.NODE_ENV==='production' ? null : (process.env.DEV_OTP_CODE||'123456');}
async function issue(phoneNumber,purpose){
  const code=devCode(); const actual=code || String(Math.floor(100000+Math.random()*900000));
  const hash=await bcrypt.hash(actual,10); await query("UPDATE otp_challenges SET consumed_at=now() WHERE phone_e164=$1 AND purpose=$2 AND consumed_at IS NULL",[phoneNumber,purpose]);
  await query("INSERT INTO otp_challenges(phone_e164,code_hash,purpose,expires_at) VALUES($1,$2,$3,now()+interval '5 minutes')",[phoneNumber,hash,purpose]);
  return code ? {expiresInSeconds:300,devCode:code} : {expiresInSeconds:300};
}
export async function requestOtp(req,res){const p=z.object({phone,purpose:z.enum(['REGISTER','LOGIN','ADD_PHONE']).default('LOGIN')}).parse(req.body); if(p.purpose==='REGISTER'||p.purpose==='LOGIN'){const r=await query('SELECT id FROM user_phones WHERE phone_e164=$1 AND verified_at IS NOT NULL',[p.phone]); if(p.purpose==='REGISTER'&&r.rowCount) return fail(res,409,'PHONE_ALREADY_REGISTERED','Phone number is already registered'); if(p.purpose==='LOGIN'&&!r.rowCount) return fail(res,404,'ACCOUNT_NOT_FOUND','No verified account exists for this phone');} return ok(res,await issue(p.phone,p.purpose));}
export async function verifyOtp(req,res){const p=z.object({phone,code:otp,purpose:z.enum(['REGISTER','LOGIN'])}).parse(req.body); const r=await query("SELECT * FROM otp_challenges WHERE phone_e164=$1 AND purpose=$2 AND consumed_at IS NULL AND expires_at>now() ORDER BY created_at DESC LIMIT 1",[p.phone,p.purpose]); if(!r.rowCount) return fail(res,400,'OTP_INVALID','OTP is invalid or expired'); const c=r.rows[0]; if(c.attempts>=5)return fail(res,429,'OTP_ATTEMPTS_EXCEEDED','Too many OTP attempts'); if(!(await bcrypt.compare(p.code,c.code_hash))){await query('UPDATE otp_challenges SET attempts=attempts+1 WHERE id=$1',[c.id]);return fail(res,400,'OTP_INVALID','OTP is invalid or expired');}
  return await withTransaction(async client=>{await client.query('UPDATE otp_challenges SET consumed_at=now() WHERE id=$1',[c.id]); let u=(await client.query('SELECT u.id,u.first_name,u.last_name,u.email FROM users u JOIN user_phones p ON p.user_id=u.id WHERE p.phone_e164=$1 AND p.verified_at IS NOT NULL',[p.phone])).rows[0]; if(p.purpose==='REGISTER'&&!u){u=(await client.query('INSERT INTO users(first_name,last_name) VALUES($1,$2) RETURNING id,first_name,last_name,email',['Pending','Passenger'])).rows[0]; await client.query('INSERT INTO user_phones(user_id,phone_e164,verified_at) VALUES($1,$2,now())',[u.id,p.phone]);} else if(u && p.purpose==='LOGIN') await client.query('UPDATE user_phones SET verified_at=COALESCE(verified_at,now()) WHERE user_id=$1 AND phone_e164=$2',[u.id,p.phone]); return ok(res,{accessToken:token(u.id),tokenType:'Bearer',expiresIn:env.JWT_EXPIRES_IN,profileComplete:u.first_name!=='Pending'&&u.last_name!=='Passenger',user:u});});}
export async function completeProfile(req,res){const p=profile.parse(req.body); const r=await query('UPDATE users SET first_name=$1,last_name=$2,email=$3,date_of_birth=$4,national_id=$5,student_info=$6,company_info=$7,updated_at=now() WHERE id=$8 RETURNING id,first_name,last_name,email,date_of_birth,national_id,student_info,company_info',[p.firstName,p.lastName,p.email||null,p.dateOfBirth||null,p.nationalId||null,p.studentInfo||{},p.companyInfo||{},req.passenger.id]); ok(res,r.rows[0]);}
export async function me(req,res){const u=await query('SELECT id,first_name AS "firstName",last_name AS "lastName",email,date_of_birth AS "dateOfBirth",national_id AS "nationalId",student_info AS "studentInfo",company_info AS "companyInfo" FROM users WHERE id=$1',[req.passenger.id]); const phones=await query('SELECT phone_e164 AS phone,verified_at AS "verifiedAt" FROM user_phones WHERE user_id=$1 ORDER BY created_at',[req.passenger.id]); ok(res,{...u.rows[0],phones:phones.rows});}
export async function addPhone(req,res){const p=z.object({phone}).parse(req.body); const r=await query('SELECT 1 FROM user_phones WHERE phone_e164=$1 AND verified_at IS NOT NULL',[p.phone]); if(r.rowCount)return fail(res,409,'PHONE_ALREADY_REGISTERED','Phone number is already registered'); return ok(res,await issue(p.phone,'ADD_PHONE'));}
export async function verifyAdditionalPhone(req,res){const p=z.object({phone,code:otp}).parse(req.body); const r=await query("SELECT * FROM otp_challenges WHERE phone_e164=$1 AND purpose='ADD_PHONE' AND consumed_at IS NULL AND expires_at>now() ORDER BY created_at DESC LIMIT 1",[p.phone]); if(!r.rowCount)return fail(res,400,'OTP_INVALID','OTP is invalid or expired'); if(!(await bcrypt.compare(p.code,r.rows[0].code_hash)))return fail(res,400,'OTP_INVALID','OTP is invalid or expired'); await withTransaction(async client=>{await client.query('UPDATE otp_challenges SET consumed_at=now() WHERE id=$1',[r.rows[0].id]); await client.query('INSERT INTO user_phones(user_id,phone_e164,verified_at) VALUES($1,$2,now())',[req.passenger.id,p.phone]);}); ok(res,{phone:p.phone,verified:true});}
