'use client';
import {useEffect,useState} from 'react';import{api}from'../../lib/api';
export default function Account(){const[phone,setPhone]=useState(''),[code,setCode]=useState(''),[step,setStep]=useState(1),[profile,setProfile]=useState(null),[form,setForm]=useState({firstName:'',lastName:'',email:''}),[prefs,setPrefs]=useState(null),[newPhone,setNewPhone]=useState(''),[phoneCode,setPhoneCode]=useState(''),[phoneStep,setPhoneStep]=useState(1),[err,setErr]=useState(''),[notice,setNotice]=useState('');const token=()=>typeof window!=='undefined'&&localStorage.getItem('passenger_token');
 const load=()=>Promise.all([api('/api/v1/passenger/me'),api('/api/v1/passenger/notification-preferences')]).then(([p,n])=>{setProfile(p);setForm({firstName:p.firstName||'',lastName:p.lastName||'',email:p.email||''});setPrefs(n)}).catch(e=>setErr(e.message));useEffect(()=>{if(token())load()},[]);
 async function request(){setErr('');try{const r=await api('/api/v1/auth/passenger/otp/request',{method:'POST',body:JSON.stringify({phone,purpose:'LOGIN'})});setStep(2);if(r.devCode)setCode(r.devCode)}catch(e){setErr(e.message)}}async function verify(){setErr('');try{const r=await api('/api/v1/auth/passenger/otp/verify',{method:'POST',body:JSON.stringify({phone,code,purpose:'LOGIN'})});localStorage.setItem('passenger_token',r.accessToken);location.reload()}catch(e){setErr(e.message)}}
 async function save(e){e.preventDefault();setErr('');try{await api('/api/v1/passenger/me',{method:'PATCH',body:JSON.stringify({firstName:form.firstName,lastName:form.lastName,email:form.email||undefined})});setNotice('Profile updated.');load()}catch(e){setErr(e.message)}}
 async function pref(k,v){try{const n=await api('/api/v1/passenger/notification-preferences',{method:'PATCH',body:JSON.stringify({[k]:v})});setPrefs(n)}catch(e){setErr(e.message)}}
 async function addPhone(){try{const r=await api('/api/v1/passenger/phones',{method:'POST',body:JSON.stringify({phone:newPhone})});setPhoneStep(2);if(r.devCode)setPhoneCode(r.devCode);setNotice('Verification code requested.')}catch(e){setErr(e.message)}}async function verifyPhone(){try{await api('/api/v1/passenger/phones/verify',{method:'POST',body:JSON.stringify({phone:newPhone,code:phoneCode})});setNewPhone('');setPhoneCode('');setPhoneStep(1);setNotice('Phone verified and added.');load()}catch(e){setErr(e.message)}}
 function logout(){localStorage.removeItem('passenger_token');location.reload()}
 if(!profile)return <main className="container"><div className="auth card"><span className="eyebrow">Passenger account</span><h1>Sign in</h1><p className="muted">Use a verified Algerian mobile number. We’ll send a one-time code.</p><input className="input" placeholder="+213…" value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel"/>{step===1?<button className="btn" onClick={request} disabled={!phone}>Send OTP</button>:<><input className="input" inputMode="numeric" maxLength={6} placeholder="6-digit OTP" value={code} onChange={e=>setCode(e.target.value)}/><div className="row"><button className="btn secondary" onClick={()=>setStep(1)}>Change number</button><button className="btn" onClick={verify} disabled={code.length<4}>Verify</button></div></>}{err&&<p className="error">{err}</p>}</div></main>;
 return <main className="container"><div className="title"><div><span className="eyebrow">Passenger account</span><h1>My account</h1></div><button className="btn secondary" onClick={logout}>Sign out</button></div>{err&&<p className="error">{err}</p>}{notice&&<p className="success">{notice}</p>}<div className="grid"><form className="card" onSubmit={save}><h2>Profile</h2><input className="input" placeholder="First name" value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})} required/><input className="input" placeholder="Last name" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})} required/><input className="input" placeholder="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button className="btn">Save profile</button></form><div className="card"><h2>Verified phones</h2><div className="list">{profile.phones?.map(p=><div className="row" key={p.phone}><span>{p.phone}</span><span className="badge">Verified</span></div>)||<p className="muted">None</p>}</div><hr/><input className="input" placeholder="Add another +213…" value={newPhone} onChange={e=>setNewPhone(e.target.value)}/>{phoneStep===1?<button className="btn secondary" onClick={addPhone} disabled={!newPhone}>Send verification</button>:<><input className="input" inputMode="numeric" placeholder="Verification code" value={phoneCode} onChange={e=>setPhoneCode(e.target.value)}/><button className="btn" onClick={verifyPhone}>Verify phone</button></>}</div></div><div className="card"><h2>Notification preferences</h2>{prefs&&Object.entries({pushEnabled:'Push',smsEnabled:'SMS',whatsappEnabled:'WhatsApp',emailEnabled:'Email',serviceAlertsEnabled:'Service alerts',promotionalEnabled:'Promotions'}).map(([k,l])=><label className="check" key={k}><input type="checkbox" checked={!!prefs[k]} onChange={e=>pref(k,e.target.checked)}/><span>{l}</span></label>)}</div></main>}
