'use client';
import {useEffect,useMemo,useState} from 'react';
import {QRCodeSVG} from 'qrcode.react';
import {api} from '../../lib/api';

export default function Tickets(){
 const [offers,setOffers]=useState([]),[tickets,setTickets]=useState([]),[payments,setPayments]=useState([]),[refunds,setRefunds]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[err,setErr]=useState(''),[notice,setNotice]=useState(''),[refund,setRefund]=useState(null);
 const logged=typeof window!=='undefined'&&!!localStorage.getItem('passenger_token');
 const load=async()=>{if(!logged){setLoading(false);return}setLoading(true);setErr('');try{const [o,t,p,r]=await Promise.all([api('/api/v1/ticketing/offers'),api('/api/v1/passenger/tickets'),api('/api/v1/passenger/payments'),api('/api/v1/passenger/refunds')]);setOffers(o||[]);setTickets(t||[]);setPayments(p||[]);setRefunds(r||[])}catch(e){setErr(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const pending=useMemo(()=>payments.filter(p=>p.status==='PENDING'),[payments]);
 async function createPayment(o){setBusy(o.id);setErr('');setNotice('');try{const p=await api('/api/v1/passenger/payments',{method:'POST',body:JSON.stringify({amountDzd:Number(o.priceDzd),provider:'CASH',providerReference:`WEB-${Date.now()}`})});setNotice(`Payment ${p.id} created. Once the payment is marked PAID, you can issue the ticket.`);await load()}catch(e){setErr(e.message)}finally{setBusy('')}}
 async function issueTicket(o,p){setBusy(`${o.id}:${p.id}`);setErr('');try{const t=await api('/api/v1/passenger/tickets',{method:'POST',body:JSON.stringify({offerId:o.id,paymentId:p.id})});setSelected(t);setNotice('Ticket issued successfully. Keep the QR code available for boarding.');await load()}catch(e){setErr(e.message)}finally{setBusy('')}}
 async function requestRefund(){if(!refund)return;setBusy('refund');try{await api('/api/v1/passenger/refunds',{method:'POST',body:JSON.stringify({paymentId:refund.paymentId,requestedAmountDzd:Number(refund.amount),reason:refund.reason})});setRefund(null);setNotice('Refund request submitted.');await load()}catch(e){setErr(e.message)}finally{setBusy('')}}
 if(!logged)return <main className="container"><div className="hero card"><span className="eyebrow">Passenger</span><h1>Tickets & payments</h1><p className="muted">Sign in to purchase, view and validate your tickets.</p><a className="btn" href="/account">Sign in</a></div></main>;
 return <main className="container"><div className="title"><div><span className="eyebrow">Passenger wallet</span><h1>Tickets</h1></div><button className="btn secondary" onClick={load}>Refresh</button></div>{loading&&<div className="card">Loading your wallet…</div>}{err&&<p className="error">{err}</p>}{notice&&<p className="success">{notice}</p>}
 <h2>Available tickets</h2><div className="grid">{offers.map(o=><div className="card" key={o.id}><div className="title"><b>{o.name}</b><span className="badge">{o.ticketType}</span></div><h2>{o.priceDzd} DZD</h2><p className="muted">Active offer</p><button className="btn" disabled={busy===o.id} onClick={()=>createPayment(o)}>{busy===o.id?'Creating…':'Create payment'}</button></div>)}</div>
 <h2>Payments</h2><div className="list">{payments.length?payments.map(p=><div className="card" key={p.id}><div className="title"><b>{p.amountDzd} DZD</b><span className="badge">{p.status}</span></div><p>{p.provider} · {p.providerReference||'No provider reference'}</p>{p.status==='PAID'&&<div className="row"><select className="input" defaultValue=""><option value="">Select ticket offer to issue</option>{offers.filter(o=>Number(o.priceDzd)===Number(p.amountDzd)).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><button className="btn" onClick={e=>{const id=e.currentTarget.previousElementSibling.value;const o=offers.find(x=>x.id===id);if(o)issueTicket(o,p)}}>Issue ticket</button></div>}{['PAID','PARTIALLY_REFUNDED'].includes(p.status)&&<button className="btn secondary" onClick={()=>setRefund({paymentId:p.id,amount:p.amountDzd,reason:''})}>Request refund</button>}</div>):<p className="muted">No payments yet.</p>}</div>
 <h2>My tickets</h2><div className="grid">{tickets.map(t=><div className="card" key={t.id}><div className="title"><b>{t.name}</b><span className="badge">{t.status}</span></div><p>{t.ticketType} · {t.priceDzd} DZD</p><p className="small">Valid {new Date(t.validFrom).toLocaleString()} → {new Date(t.validUntil).toLocaleString()}</p><button className="btn" onClick={()=>setSelected(t)}>View ticket</button></div>)}</div>
 <h2>Refund requests</h2><div className="list">{refunds.length?refunds.map(r=><div className="card" key={r.id}><b>{r.requestedAmountDzd} DZD</b><p>{r.status} · {r.reason}</p></div>):<p className="muted">No refund requests.</p>}</div>
 {selected&&<div className="modal"><div className="modal-card"><div className="title"><h2>{selected.name}</h2><button className="icon" onClick={()=>setSelected(null)}>×</button></div>{selected.qrToken?<><QRCodeSVG value={selected.qrToken} size={240} includeMargin/><p className="small">Present this QR code to the bus validator.</p></>:<p className="muted">The QR token is only returned when this ticket is issued in the current session. For security, it is not recoverable from the ticket list.</p>}<p className="small">Ticket ID: {selected.id}</p></div></div>}
 {refund&&<div className="modal"><div className="modal-card"><h2>Request refund</h2><input className="input" type="number" min="0.01" max={refund.amount} value={refund.amount} onChange={e=>setRefund({...refund,amount:e.target.value})}/><textarea className="input" placeholder="Reason" value={refund.reason} onChange={e=>setRefund({...refund,reason:e.target.value})}/><div className="row"><button className="btn secondary" onClick={()=>setRefund(null)}>Cancel</button><button className="btn" disabled={!refund.reason||busy==='refund'} onClick={requestRefund}>Submit</button></div></div></div>}
 </main>
}
